version: "3.7"

volumes:

  db:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/amounadi/data/DB

  wb:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/amounadi/data/WB

networks:
  mynetwork:
    driver: bridge

services:
  
  nginx:
    build: 
      context: ./requirements/nginx
      args:
      - DOMAIN_NAME=${DOMAIN_NAME:-def}
    image: nginx:my 
    container_name: co_nginx
    env_file : ./.env
    ports:
      - 443:443
    volumes:
      - wb:/usr/share/nginx/html
    networks:
      - mynetwork
    depends_on:
      - ftp
    restart: always

  
  mariadb:
    build:
      context: ./requirements/mariadb
      args:
        - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-default_root_password}
        - DB_USER=${DB_USER:-default_user}
        - DB_USER_PASSWORD=${DB_USER_PASSWORD:-default_password}
        - DB_DATABASE=${DB_DATABASE:-default_database}
    image: mariadb:my 
    container_name: co_mariadb
    env_file : ./.env
    volumes:
      - db:/var/lib/mysql
    networks:
      - mynetwork
    restart: always

    
  wordpress:
    build :
      context : ./requirements/wordpress
      args:
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-default_root_password}
      - DB_USER=${DB_USER:-default_user}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD:-default_password}
      - DB_DATABASE=${DB_DATABASE:-default_database}
      - url=${url:-def}
      - title=${title:-def}
      - wordpress_admin=${wordpress_admin:-def}
      - wordpress_password=${wordpress_password:-def}
      - admin_email=${admin_email:-def}
      - DB_HOST=co_mariadb
      - FTP_HOST=${FTP_HOST:-def}
      - FTP_USER=${FTP_USER:-def}
      - FTP_PASS=${FTP_PASS:-def}
    image: wordpress:my
    container_name: co_wordpress
    env_file : ./.env
    volumes:
      - wb:/usr/share/nginx/html
    networks:
      - mynetwork
    depends_on:
      - mariadb
    restart: always

    
  adminer:
    build:
      context: ./requirements/bonus/adminer
    image: adminer:my
    container_name: co_adminer
    networks:
      - mynetwork
    restart: always


  ftp:
    build:
      context: ./requirements/bonus/ftp
      args : 
        - FTP_HOST=${FTP_HOST:-def}
        - FTP_USER=${FTP_USER:-def}
        - FTP_PASS=${FTP_PASS:-def}
    image: ftp:my
    container_name: co_ftp
    env_file : ./.env
    volumes:
      - wb:/home/
    networks:
      - mynetwork
    depends_on:
      - wordpress
    restart: always

  
  static:
    build:
      context: ./requirements/bonus/static
    image: static:my
    container_name: co_static
    networks:
      - mynetwork
    depends_on:
      - wordpress
    restart: always
 
  
  portainer:
    build:
      context: ./requirements/bonus/portainer
    image: portainer:my
    container_name: co_portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - mynetwork
    depends_on:
      - wordpress
    restart: always

  redis:
    build:
      context: ./requirements/bonus/redis
    image: redis:my
    container_name: co_redis
    networks:
      - mynetwork
    depends_on:
      - wordpress
      - nginx
    volumes:
      - wb:/home/
    restart: always
   
 



