FROM debian:buster

RUN apt-get update && apt-get install redis-server -y

COPY tools/redis.conf /etc/redis/redis.conf

CMD ["redis-server", "--daemonize", "no", "--protected-mode", "no", "--bind", "0.0.0.0", "--port", "6379"]
